// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0Rao0oteI8v59YAgjNSJwRIYn3U-n8N4',
    appId: '1:527688732675:web:851927b2c38f5a688bfe36',
    messagingSenderId: '527688732675',
    projectId: 'ishop2024-f69cc',
    authDomain: 'ishop2024-f69cc.firebaseapp.com',
    storageBucket: 'ishop2024-f69cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQOk3aRZXhrNOCIPCHoFruD_Y0ec94iWI',
    appId: '1:527688732675:android:cdcf532a0ed234928bfe36',
    messagingSenderId: '527688732675',
    projectId: 'ishop2024-f69cc',
    storageBucket: 'ishop2024-f69cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDkm_IRuLdjgwF9LdxO-KogmG32R5JRrA',
    appId: '1:527688732675:ios:b457f664b0ff21058bfe36',
    messagingSenderId: '527688732675',
    projectId: 'ishop2024-f69cc',
    storageBucket: 'ishop2024-f69cc.appspot.com',
    androidClientId: '527688732675-fiumagvieol2lbp41av0u1ks62qjjc3c.apps.googleusercontent.com',
    iosClientId: '527688732675-j8g74fd1840dgaf8ts0bq1v73cmbvmqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.iShop',
  );

}